import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
test("solve, retry, resume, solution, progress and review", async ({ page }) => {
  await page.goto("/question/?id=L001-Q01");
  await page.getByLabel(/sisa = tersedia/).check();
  await page.getByRole("button", { name: "Lanjutkan", exact: true }).click();
  await page.getByLabel("Sisa tersedia", { exact: true }).fill("100");
  await page.waitForTimeout(750);
  await page.reload();
  await page.getByRole("button", { name: "Perhitungan", exact: true }).click();
  await expect(page.getByLabel("Sisa tersedia", { exact: true })).toHaveValue("100");
  await page.getByRole("button", { name: "Periksa jawaban" }).click();
  await expect(page.getByText("Ada langkah yang perlu ditinjau.")).toBeVisible();
  await expect(page.getByText("122", { exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Revisi jawaban" }).click();
  await page.getByRole("button", { name: "Perhitungan", exact: true }).click();
  await page.getByLabel("Sisa tersedia", { exact: true }).fill("122");
  await page.getByRole("button", { name: "Periksa jawaban" }).click();
  await expect(page.getByText("Checkpoint otomatis benar.")).toBeVisible();
  await page.getByRole("link", { name: "Buka pembahasan" }).click();
  await expect(page.getByRole("heading", { name: "Hasil checkpoint" })).toBeVisible();
  await expect(page.getByText("Sisa tersedia = 122 item", { exact: true })).toBeVisible();
  await page.goto("/progress/"); await expect(page.getByText("2 attempts tersimpan")).toBeVisible();
  await page.goto("/mistakes/"); await expect(page.getByText("wrong calculation", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Coba lagi" }).click();
  await page.getByLabel(/sisa = tersedia/).check();
  await page.getByRole("button", { name: "Lanjutkan", exact: true }).click();
  await page.getByLabel("Sisa tersedia", { exact: true }).fill("122");
  await page.getByRole("button", { name: "Periksa jawaban" }).click();
  await expect(page.getByText("Checkpoint otomatis benar.")).toBeVisible();
  await page.goto("/mistakes/"); await page.getByLabel("Status", { exact: true }).selectOption("resolved");
  await expect(page.getByText(/Terselesaikan/, { exact: false }).last()).toBeVisible();
});
test("library contains all levels and direct solution stays gated", async ({ page }) => {
  await page.goto("/problems/"); await expect(page.getByText("5.000 soal ditemukan")).toBeVisible();
  await page.getByLabel("Level", { exact: true }).selectOption("100"); await expect(page.getByText("50 soal ditemukan")).toBeVisible();
  await page.goto("/solution/?id=L001-Q01"); await expect(page.getByRole("heading", { name: "Pembahasan belum dibuka" })).toBeVisible();
});
for (const width of [360, 768, 1024, 1280]) test(`responsive ${width}px and accessible shell`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 }); await page.goto("/");
  await expect(page.getByRole("heading", { level: 1 })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `test-results/home-${width}.png`, fullPage: true });
  await page.goto("/question/?id=L001-Q01"); await expect(page.getByRole("heading", { name: "Target Recovery" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const results = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(results.violations).toEqual([]);
});
test("cached solve route works offline", async ({ page, context }) => {
  await page.goto("/question/?id=L001-Q01");
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.reload(); await expect(page.getByRole("heading", { name: "Target Recovery" })).toBeVisible();
  await context.setOffline(true); await page.reload();
  await expect(page.getByRole("heading", { name: "Target Recovery" })).toBeVisible();
  await page.getByLabel(/sisa = tersedia/).check();
  await page.getByRole("button", { name: "Lanjutkan", exact: true }).click();
  await page.getByLabel("Sisa tersedia", { exact: true }).fill("122");
  await page.getByRole("button", { name: "Periksa jawaban" }).click();
  await expect(page.getByText("Checkpoint otomatis benar.")).toBeVisible();
});
