import { describe, expect, it } from "vitest";
import fs from "node:fs";
import type { Question, Responses } from "@/domain/question/types";
import { grade } from "@/domain/assessment/engine";
const bank = Array.from({ length: 100 }, (_, i) => JSON.parse(fs.readFileSync(`public/content/level-${String(i + 1).padStart(3, "0")}.json`, "utf8")) as Question[]);
describe("full bank", () => {
  it("has 5000 unique, valid question records with solutions and nonempty interactions", () => { expect(bank.flat()).toHaveLength(5000); expect(new Set(bank.flat().map(q => q.id)).size).toBe(5000); for (const level of bank) { expect(level).toHaveLength(50); for (const q of level) { expect(q.hints).toHaveLength(5); expect(q.solution.calculations.length).toBeGreaterThan(0); const responses: Responses = {}; for (const i of q.interactions) { const v = i.validator; responses[i.id] = v.kind === "numeric" ? { text: String(v.value), unit: v.unit } : v.kind === "choice" ? { text: v.value } : v.kind === "equation" ? { selections: v.tokens } : v.kind === "rubric" ? { text: "Alasan disertai data", rubric: v.criteria.map(() => 2) } : { selections: v.values }; } expect(grade(q, responses).every(d => d.score === 100), q.id).toBe(true); } } });
  it("recomputes arithmetic against original scalar authoring keys", () => { for (const level of bank.slice(0, 20)) for (const q of level) { if (!/^-?\d+(\.\d+)?$/.test(q.authoring.originalKey)) continue; const fields = q.interactions.filter(i => i.validator.kind === "numeric"); const output = q.level === 14 ? fields.at(-1)! : fields[0]; if (output.validator.kind !== "numeric") throw Error(); expect(output.validator.value, q.id).toBeCloseTo(Number(q.authoring.originalKey), 7); } });
  it("computes representative independent reference results", () => {
    const answer = (level: number, index = 0) => { const i = bank[level - 1][0].interactions.filter(i => i.validator.kind === "numeric")[index]; return i.validator.kind === "numeric" ? i.validator.value : NaN; };
    expect(answer(22)).toBe(20); expect(answer(22, 1)).toBe(11); expect(answer(26)).toBe(236); expect(answer(27, 1)).toBe(910); expect(answer(28, 2)).toBeCloseTo(253.44); expect(answer(29)).toBeCloseTo(Math.sqrt(490)); expect(answer(31)).toBe(70); expect(answer(32)).toBeCloseTo(44 / 117); expect(answer(33)).toBeCloseTo(.057395628); expect(answer(36)).toBeCloseTo(47.06); expect(answer(37)).toBe(5); expect(answer(40)).toBe(200); expect(answer(41)).toBeCloseTo(50.1); expect(answer(43)).toBeCloseTo(4.2); expect(answer(44)).toBeCloseTo(8052.55, 2); expect(answer(45)).toBeCloseTo(946.43, 2); expect(answer(46, 1)).toBeCloseTo(73.4); expect(answer(47, 2)).toBe(5); expect(answer(49)).toBeCloseTo(82.05); expect(answer(63)).toBe(5); expect(answer(64)).toBe(15); expect(answer(71, 1)).toBe(12); expect(answer(100)).toBeCloseTo(453.6); expect(answer(100, 2)).toBeCloseTo(-177.12);
  });
  it("labels missing-source assumptions and preserves original keys", () => { for (const level of [40, 51, 66, 76, 81, 90]) { const q = bank[level - 1][0]; expect(q.authoring.notes.length).toBeGreaterThan(0); expect(q.authoring.originalKey.length).toBeGreaterThan(0); expect(q.dataBlocks.length).toBeGreaterThan(0); } });
});
