"use client";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from "recharts";
import type { VisualizationSpec } from "@/domain/question/types";
import { formatNumber } from "@/lib/utils";
export default function ChartBlock({ spec }: { spec: VisualizationSpec }) {
  const { rows, kind } = spec;
  const common = <><CartesianGrid strokeDasharray="3 3" stroke="var(--border)" /><XAxis dataKey="name" fontSize={11} minTickGap={24} /><YAxis fontSize={11} width={46} /><Tooltip contentStyle={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 6 }} />{rows.some(r => r.secondary !== undefined) && <Legend />}</>;
  const nodes: Record<string, [number, number]> = { A: [40, 120], B: [180, 40], C: [180, 210], D: [330, 120] };
  let visual;
  if (spec.edges && ["network", "flow", "supply-chain"].includes(kind)) visual = <svg viewBox="0 0 370 250" role="img" aria-label={spec.summary}><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="var(--accent)" /></marker></defs>{spec.edges.map((e, i) => { const a = nodes[e.from], b = nodes[e.to]; return <g key={i}><line x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke="var(--accent)" strokeWidth="2" /><text x={(a[0] + b[0]) / 2 + 8} y={(a[1] + b[1]) / 2 - 6} fill="var(--text)" fontSize="13">{e.value} →</text></g>; })}{Object.entries(nodes).map(([name, [x, y]]) => <g key={name}><circle cx={x} cy={y} r="19" fill="var(--accent-soft)" stroke="var(--accent)" /><text x={x} y={y + 5} textAnchor="middle" fill="var(--text)">{name}</text></g>)}</svg>;
  else if (kind === "box") {
    const sorted = rows.map(r => r.value).sort((a,b)=>a-b), quantile=(p:number)=>{const x=(sorted.length-1)*p,lo=Math.floor(x);return sorted[lo]+(sorted[Math.ceil(x)]-sorted[lo])*(x-lo);};
    const min=sorted[0],max=sorted.at(-1)!,x=(v:number)=>30+(v-min)/(max-min||1)*300;
    visual=<svg viewBox="0 0 360 150" role="img" aria-label="Box plot dengan whisker minimum dan maksimum"><line x1={x(min)} x2={x(max)} y1={65} y2={65} stroke="var(--accent)"/><rect x={x(quantile(.25))} y={40} width={Math.max(1,x(quantile(.75))-x(quantile(.25)))} height={50} fill="var(--accent-soft)" stroke="var(--accent)"/>{[min,quantile(.5),max].map((v,i)=><line key={i} x1={x(v)} x2={x(v)} y1={40} y2={90} stroke="var(--accent)" strokeWidth={2}/>)}{[min,quantile(.25),quantile(.5),quantile(.75),max].map((v,i)=><text key={i} x={x(v)} y={i%2?135:115} textAnchor="middle" fontSize={11} fill="var(--text)">{formatNumber(v)}</text>)}</svg>;
  }
  else if (kind === "histogram") {
    const values=rows.map(r=>r.value),min=Math.min(...values),max=Math.max(...values),count=Math.max(1,Math.ceil(Math.sqrt(values.length))),width=(max-min||1)/count;
    const bins=Array.from({length:count},(_,i)=>({name:`${formatNumber(min+i*width)}–${formatNumber(min+(i+1)*width)}`,value:values.filter(v=>Math.min(count-1,Math.floor((v-min)/width))===i).length}));
    visual=<ResponsiveContainer width="100%" height={260}><BarChart data={bins} barCategoryGap={0}>{common}<Bar dataKey="value" name="Frekuensi" fill="var(--accent)" isAnimationActive={false}/></BarChart></ResponsiveContainer>;
  }
  else if (["schedule", "timeline"].includes(kind)) {
    const max=Math.max(...rows.map(r=>(r.secondary??0)+r.value),1);
    visual=<div className="matrix-view">{rows.map((r,i)=><div key={i}><strong>{r.name}</strong><div style={{flex:1,background:"var(--elevated)",position:"relative",height:30}}><div style={{position:"absolute",left:`${(r.secondary??0)/max*100}%`,width:`${r.value/max*100}%`,height:30,background:"var(--accent-soft)",border:"1px solid var(--accent)",textAlign:"center"}}>{formatNumber(r.value)}</div></div></div>)}<p className="text-xs">As horizontal: waktu dari 0 sampai {formatNumber(max)} {spec.unit}. Awal bar mengikuti waktu mulai yang diberikan.</p></div>;
  }
  else if (kind === "matrix") visual = <div className="matrix-view">{rows.map((r, i) => <div key={i}><strong>{r.name}</strong><span style={{ background: "var(--accent-soft)" }}>{formatNumber(r.value)}</span>{r.secondary !== undefined && <span>{formatNumber(r.secondary)}</span>}</div>)}</div>;
  else if (["flow","supply-chain"].includes(kind)) visual=<div className="matrix-view">{rows.map((r,i)=><div key={i}><strong>{r.name}</strong><span>{formatNumber(r.value)}{r.secondary!==undefined?` / ${formatNumber(r.secondary)}`:""} {spec.unit}</span>{i<rows.length-1&&<b aria-label="langkah berikutnya">↓</b>}</div>)}</div>;
  else if (kind === "feasible") {
    const max=Math.max(...rows.flatMap(r=>[r.value,r.secondary??0]),1),x=(v:number)=>35+v/max*270,y=(v:number)=>230-v/max*200;
    visual=<svg viewBox="0 0 340 270" role="img" aria-label="Polygon feasible dari titik batas model"><path d="M35 15V230H320" stroke="var(--muted)" fill="none"/><polygon points={rows.map(r=>`${x(r.value)},${y(r.secondary??0)}`).join(" ")} fill="var(--accent-soft)" stroke="var(--accent)"/>{rows.map((r,i)=><circle key={i} cx={x(r.value)} cy={y(r.secondary??0)} r={4} fill="var(--accent)"/>)}<text x={160} y={260} fill="var(--text)">x ({spec.unit})</text><text x={8} y={20} fill="var(--text)">y</text></svg>;
  }
  else if (["geometry", "factory"].includes(kind)) visual = <svg viewBox="0 0 360 220" role="img" aria-label={spec.summary}><path d="M55 170L240 170L305 115L120 115ZM55 170V75L120 25L305 25V115M55 75H240V170M240 75L305 25" stroke="var(--accent)" strokeWidth="2" fill="var(--accent-soft)" /><text x="120" y="197" fill="var(--text)">{rows[0]?.value} m</text><text x="262" y="160" fill="var(--text)">{rows[1]?.value} m</text><text x="12" y="130" fill="var(--text)">{rows[2]?.value} m</text></svg>;
  else if (kind === "coordinate" || kind === "scatter" || kind === "vector") visual = <ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" dataKey="value" name="x" /><YAxis type="number" dataKey="secondary" name="y" /><Tooltip cursor={{ strokeDasharray: "3 3" }} /><Scatter data={rows} fill="var(--accent)" line={kind !== "scatter"} /></ScatterChart></ResponsiveContainer>;
  else if (["line", "function", "derivative", "financial"].includes(kind)) visual = <ResponsiveContainer width="100%" height={260}><LineChart data={rows}>{common}<Line dataKey="value" name="Nilai" stroke="var(--accent)" strokeWidth={2} dot={rows.length < 15} isAnimationActive={false} />{rows.some(r => r.secondary !== undefined) && <Line dataKey="secondary" name="Pembanding" stroke="var(--ochre)" strokeDasharray="5 3" isAnimationActive={false} />}</LineChart></ResponsiveContainer>;
  else if (["distribution", "integral", "feasible"].includes(kind)) visual = <ResponsiveContainer width="100%" height={260}><AreaChart data={rows}>{common}<Area dataKey="value" name="Nilai" stroke="var(--accent)" fill="var(--accent-soft)" isAnimationActive={false} /></AreaChart></ResponsiveContainer>;
  else visual = <ResponsiveContainer width="100%" height={260}><BarChart data={rows}>{common}<Bar dataKey="value" name="Nilai / demand" fill="var(--accent)" radius={[3, 3, 0, 0]} isAnimationActive={false} />{rows.some(r => r.secondary !== undefined) && <Bar dataKey="secondary" name="Kapasitas / pembanding" fill="var(--ochre)" radius={[3, 3, 0, 0]} isAnimationActive={false} />}</BarChart></ResponsiveContainer>;
  return <figure className="chart-block"><figcaption><strong>{spec.title}</strong><small>Satuan: {spec.unit}</small></figcaption><p className="sr-only">{spec.summary}</p><div className="chart-visual">{visual}</div><details><summary>Lihat data tabel</summary><div className="table-scroll"><table><caption>{spec.summary}</caption><thead><tr><th>Data</th><th>Nilai ({spec.unit})</th>{rows.some(r => r.secondary !== undefined) && <th>Pembanding</th>}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}><th scope="row">{r.name}</th><td>{formatNumber(r.value, 5)}</td>{r.secondary !== undefined && <td>{formatNumber(r.secondary, 5)}</td>}</tr>)}</tbody></table></div></details></figure>;
}
