// Pure, deterministic authoring adapters. No evaluation of Markdown or user expressions.
export const numbers = s => [...s.matchAll(/(?<![A-Za-z])[-+]?\d+(?:\.\d+)?/g)].map(m => Number(m[0]));
const list = (s, name) => numbers(s.match(new RegExp(name + "[^\\[]*\\[([^\\]]+)\\]"))?.[1] ?? "");
const num = (s, re, index = 1) => { const m = s.match(re); if (!m) throw new Error(`Parameter tidak ditemukan: ${re} dalam ${s}`); return Number(m[index].replace(/\.$/, "")); };
const sum = a => a.reduce((x, y) => x + y, 0);
const mean = a => sum(a) / a.length;
const choose = (n, k) => { let a = 1; for (let i = 1; i <= k; i++) a *= (n - i + 1) / i; return a; };
const show = n => Number.isFinite(n) ? String(Number(n.toFixed(5))) : String(n);
function normalCDF(z) { const x = Math.abs(z), t = 1 / (1 + .2316419 * x), d = .3989422804 * Math.exp(-x * x / 2); const p = 1 - d * t * (.319381530 + t * (-.356563782 + t * (1.781477937 + t * (-1.821255978 + t * 1.330274429)))); return z < 0 ? 1 - p : p; }

export function recipe(level, s, originalKey) {
  const n = numbers(s), outputs = [], calculations = [], notes = [], visuals = [];
  let model = "", interpretation = "", decision = "", sensitivity = "Ubah satu input, hitung ulang, lalu bandingkan perubahan output terhadap perubahan input.", extra = "";
  const out = (label, value, expression, unit = "tanpa satuan", tolerance = .011) => { if (!Number.isFinite(value)) throw new Error(`Hasil tidak finite L${level}: ${label}`); outputs.push({ label, value, expression, unit, tolerance }); calculations.push({ label, expression, result: value }); };
  const chart = (kind, title, values, unit = "tanpa satuan", names) => visuals.push({ kind, title, unit, summary: `${title}. Data lengkap tersedia dalam tabel.`, rows: values.map((v, i) => ({ name: names?.[i] ?? String(i + 1), value: v })) });
  const keyUnit = s.match(/(?:\d) (item|point|pallet|lot|order|IDR|hour|case|job|kWh|people|observation|unit|trip|task|m)(?:[ .,]|$)/)?.[1] ?? "unit";
  switch (level) {
    case 1: model = "sisa = tersedia − digunakan"; out("Sisa tersedia", n[0] - n[1], `${n[0]} − ${n[1]}`, keyUnit); break;
    case 2: model = "total = output per siklus × jumlah siklus"; out("Total output", n[0] * n[1], `${n[0]} × ${n[1]}`, keyUnit); break;
    case 3: model = "bagian = total / jumlah penerima"; out("Alokasi per penerima", n[0] / n[1], `${n[0]} / ${n[1]}`, `${keyUnit}/penerima`); break;
    case 4: model = "alokasi = total × pecahan"; out("Alokasi prioritas A", n[0] * n[1] / n[2], `${n[0]} × ${n[1]}/${n[2]}`, keyUnit); break;
    case 5: model = "target = baseline × (1 + persentase/100)"; out("Target baru", n[0] * (1 + n[1] / 100), `${n[0]} × (1 + ${n[1]}/100)`, keyUnit); break;
    case 6: model = "alokasi A = total × a/(a+b)"; out("Alokasi pertama", n[2] * n[0] / (n[0] + n[1]), `${n[2]} × ${n[0]}/(${n[0]}+${n[1]})`, keyUnit); break;
    case 7: model = "kebutuhan baru = kebutuhan awal × skala"; out("Kebutuhan baru", n[1] * n[2] / n[0], `${n[1]} × ${n[2]}/${n[0]}`, keyUnit); break;
    case 8: model = "mean = jumlah nilai / jumlah pengukuran"; out("Arithmetic mean", mean(n), `(${n.join(" + ")}) / ${n.length}`, keyUnit); chart("bar", "Pengukuran", n, keyUnit); break;
    case 9: model = "jam = menit / 60"; out("Durasi", n[0] / 60, `${n[0]} / 60`, "jam"); break;
    case 10: model = "estimasi = round(jumlah/100) × 100"; out("Estimasi ratusan", Math.round(n[0] / 100) * 100, `round(${n[0]}/100) × 100`, keyUnit); interpretation = `Galat pembulatan adalah ${show(Math.abs(n[0] - Math.round(n[0] / 100) * 100))} ${keyUnit}; bandingkan dengan toleransi keputusan.`; break;
    case 11: model = "rate = target / (shift − downtime/60)"; out("Rate minimum", n[0] / (n[1] - n[2] / 60), `${n[0]} / (${n[1]} − ${n[2]}/60)`, `${keyUnit}/jam`); break;
    case 12: model = "akhir = awal × (1 + naik/100) × (1 − turun/100)"; out("Nilai akhir", n[0] * (1 + n[1]/100) * (1-n[2]/100), `${n[0]} × ${1+n[1]/100} × ${1-n[2]/100}`, keyUnit); break;
    case 13: model = "mean gabungan = (n₁μ₁ + n₂μ₂)/(n₁+n₂)"; out("Weighted mean", (n[0]*n[1]+n[2]*n[3])/(n[0]+n[2]), `(${n[0]}×${n[1]} + ${n[2]}×${n[3]})/(${n[0]}+${n[2]})`); break;
    case 14: model = "resource = ratio × demand; kilo-resource = resource/1000"; out("Total resource", n[0]*n[1], `${n[0]} × ${n[1]}`, "resource-unit"); out("Total dalam kilo", n[0]*n[1]/1000, `${show(n[0]*n[1])}/1000`, "kilo-resource-unit", .00001); break;
    case 15: model = "utilisasi = actual/capacity × 100"; out("Capacity utilization", n[0]/n[1]*100, `${n[0]}/${n[1]} × 100`, "%"); break;
    case 16: { const a = list(s, "periode").sort((a,b)=>a-b); model = "mean = Σx/n; median = nilai tengah; range = max − min"; out("Mean", mean(a), `${sum(a)} / ${a.length}`); out("Median", a[3], "nilai urutan ke-4"); out("Range", a[6]-a[0], `${a[6]} − ${a[0]}`); interpretation = "Median lebih tahan terhadap satu nilai ekstrem; mean tetap berguna untuk total/beban rata-rata."; chart("box", "Sebaran pengukuran", a); break; }
    case 17: model = "P = kasus memenuhi / seluruh kasus"; out("Estimated probability", n[1]/n[0], `${n[1]} / ${n[0]}`, "rasio", .0001); break;
    case 18: case 21: model = "x = (total − intercept)/koefisien"; out("x", (n[2]-n[0])/n[1], `(${n[2]} − ${n[0]}) / ${n[1]}`); break;
    case 19: model = "unit minimum = ceil(fixed cost / contribution margin)"; out("Minimum whole units", Math.ceil(n[0]/n[1]), `ceil(${n[0]}/${n[1]})`, "unit", 0); break;
    case 20: model = "remaining = target − selesai; capacity = waktu × rate"; out("Remaining requirement", n[0]-n[1], `${n[0]} − ${n[1]}`, "unit"); out("Kapasitas tambahan", n[2]*n[3], `${n[2]} × ${n[3]}`, "unit"); decision = n[0]-n[1] <= n[2]*n[3] ? "Target feasible tanpa intervensi." : `Target tidak feasible; kekurangan ${show(n[0]-n[1]-n[2]*n[3])} unit membutuhkan intervensi.`; break;
    case 22: model = "A+B=N; aA+bB=R"; out("A", (n[3]-n[2]*n[0])/(n[1]-n[2]), `(${n[3]} − ${n[2]}×${n[0]}) / (${n[1]}−${n[2]})`, "unit"); out("B", n[0]-outputs[0].value, `${n[0]} − ${show(outputs[0].value)}`, "unit"); break;
    case 23: model = "fixed + rate × x ≤ capacity; x bilangan bulat ≥ 0"; out("Maksimum whole units", Math.floor((n[0]-n[1])/n[2]), `floor((${n[0]}−${n[1]})/${n[2]})`, "unit", 0); break;
    case 24: model = "f(x) = ax + b"; out("f(x)", n[0]*n[2]+n[1], `${n[0]}×${n[2]}+${n[1]}`); out("Slope", n[0], "koefisien x"); out("Intercept", n[1], "f(0)"); break;
    case 25: { const demand=num(s,/demand=(\d+)/), cap=num(s,/capacity=(\d+)/), reserve=num(s,/policy=(\d+)/); model="kapasitas usable = capacity × (1 − reserve); margin = usable − demand"; out("Kapasitas usable",cap*(1-reserve/100),`${cap} × (1−${reserve}/100)`,keyUnit); out("Capacity margin",outputs[0].value-demand,`${show(outputs[0].value)} − ${demand}`,keyUnit); decision=outputs[1].value>=0?"Cadangan terpenuhi; capacity aman pada baseline.":"Capacity tidak cukup setelah cadangan; tambah kapasitas atau kurangi demand."; break; }
    case 26: { const x=num(s,/consumption (\d+)/); model="C(x) = 2 min(x,100) + 1.5 min(max(x−100,0),150) + 1.2 max(x−250,0)"; out("Progressive cost",2*Math.min(x,100)+1.5*Math.min(Math.max(x-100,0),150)+1.2*Math.max(x-250,0),`2×${Math.min(x,100)} + 1.5×${Math.min(Math.max(x-100,0),150)} + 1.2×${Math.max(x-250,0)}`,"cost-unit"); break; }
    case 27: { const a=n[0], d=n[1], k=Math.abs(n[2]); model="aₖ = a₁+(k−1)d; Sₖ=k(a₁+aₖ)/2"; out("Requirement minggu k",a+(k-1)*d,`${a}+(${k}−1)×${d}`,keyUnit); out("Cumulative requirement",k*(a+outputs[0].value)/2,`${k}×(${a}+${outputs[0].value})/2`,keyUnit); break; }
    case 28: model="A=p×l; V=A×h; net=V(1−clearance)"; out("Floor area",n[0]*n[1],`${n[0]}×${n[1]}`,"m²"); out("Volume",n[0]*n[1]*n[2],`${n[0]}×${n[1]}×${n[2]}`,"m³"); out("Net volume",outputs[1].value*(1-n[3]/100),`${outputs[1].value}×${1-n[3]/100}`,"m³"); chart("geometry","Dimensi penyimpanan",n.slice(0,3),"m",["Panjang","Lebar","Tinggi"]); break;
    case 29: model="d = √((x₂−x₁)²+(y₂−y₁)²); midpoint=(P₁+P₂)/2"; out("Distance",Math.hypot(n[2]-n[0],n[3]-n[1]),`√((${n[2]}−${n[0]})²+(${n[3]}−${n[1]})²)`,"km"); out("Midpoint x",(n[0]+n[2])/2,`(${n[0]}+${n[2]})/2`,"km"); out("Midpoint y",(n[1]+n[3])/2,`(${n[1]}+${n[3]})/2`,"km"); visuals.push({kind:"coordinate",title:"Titik layanan",unit:"km",summary:"Koordinat dua lokasi pada grid lokal.",rows:[{name:"A",value:n[0],secondary:n[1]},{name:"B",value:n[2],secondary:n[3]}]}); break;
    case 30: model="h = d tan(θ)"; out("Height",n[0]*Math.tan(n[1]*Math.PI/180),`${n[0]} × tan(${n[1]}°)`,"m"); break;
    case 31: model="C(n,k)=n!/(k!(n−k)!)"; out("Jumlah tim",choose(n[0],n[1]),`C(${n[0]},${n[1]})`,"tim",0); break;
    case 32: model="P(B|A)=P(A∩B)/P(A)"; out("P(B|A)",n[2]/n[1],`${n[2]}/${n[1]}`,"rasio",.0051); break;
    case 33: model="P(X=k)=C(n,k)pᵏ(1−p)ⁿ⁻ᵏ"; out("P(X=k)",choose(n[0],n[2])*n[1]**n[2]*(1-n[1])**(n[0]-n[2]),`C(${n[0]},${n[2]})×${n[1]}^${n[2]}×${1-n[1]}^${n[0]-n[2]}`,"rasio",.0051); chart("distribution","Distribusi binomial",Array.from({length:n[0]+1},(_,k)=>choose(n[0],k)*n[1]**k*(1-n[1])**(n[0]-k)),"probabilitas",Array.from({length:n[0]+1},(_,k)=>String(k))); break;
    case 34: model="z=(threshold−μ)/σ; P(X≤threshold)=Φ(z)"; out("z-score",(n[2]-n[0])/n[1],`(${n[2]}−${n[0]})/${n[1]}`); out("Proporsi di bawah threshold",normalCDF(outputs[0].value),`Φ(${outputs[0].value})`,"rasio",.002); chart("distribution","Densitas normal standar",Array.from({length:41},(_,i)=>Math.exp(-(((i-20)/5)**2)/2)/Math.sqrt(2*Math.PI)),"densitas",Array.from({length:41},(_,i)=>show((i-20)/5))); break;
    case 35: model="simple random sample tanpa pengembalian"; extra=`Gunakan sampling frame berisi ${n[0]} ID unik dan pilih ${n[1]} ID dengan peluang sama. Checkpoint: hitung fraksi sampling.`; out("Fraksi sampling",n[1]/n[0],`${n[1]}/${n[0]}`,"rasio"); calculations.push({label:"Desain sampling",expression:"Acak seluruh ID dengan seed yang dicatat; ambil n pertama tanpa duplikasi.",result:"Audit cakupan frame dan nonresponse; estimasikan statistik yang dinyatakan, bukan kepastian populasi."}); break;
    case 36: { const m=num(s,/mean=([\d.]+)/), se=num(s,/error=([\d.]+)/); model="CI = mean ± 1.96 × SE"; out("Batas bawah",m-1.96*se,`${m}−1.96×${se}`); out("Batas atas",m+1.96*se,`${m}+1.96×${se}`); interpretation="Dalam pengulangan sampling, sekitar 95% interval yang dibentuk dengan prosedur ini mencakup mean populasi, dengan asumsi pendekatan valid."; break; }
    case 37: { const mu=num(s,/μ0=(\d+)/), m=num(s,/mean=(\d+)/), se=num(s,/SE=([\d.]+)/); model="z = (mean−μ₀)/SE"; out("z statistic",(m-mu)/se,`(${m}−${mu})/${se}`); decision=Math.abs(outputs[0].value)>1.96?"Tolak H₀ pada pendekatan dua sisi 5%; periksa asumsi dan signifikansi praktis.":"Belum cukup bukti untuk menolak H₀; ini tidak membuktikan H₀ benar."; break; }
    case 38: model="r mengukur arah dan kekuatan hubungan linear"; out("Koefisien korelasi",num(s,/r=([-\d.]+)/),"nilai r yang diberikan", "rasio"); interpretation=`r=${outputs[0].value}: arah ${outputs[0].value<0?"negatif":"positif"}; |r|=${Math.abs(outputs[0].value)}. Confounding atau selection bias dapat menjelaskan hubungan; tidak membuktikan sebab akibat.`; break;
    case 39: { const m=s.match(/ŷ=([\d.]+)\+([\d.]+)x/); const x=num(s,/x=(\d+)/); model="ŷ = intercept + slope × x"; out("Prediction",Number(m[1])+Number(m[2])*x,`${m[1]}+${m[2]}×${x}`); break; }
    case 40: model="expected loss = probability × loss"; out("Expected loss",n[0]*n[1],`${n[0]}×${n[1]}`,"cost-unit"); decision=n[0]*n[1] > n[2]?"Pilih preventive action jika benar-benar menghilangkan risiko.":"Tanpa action lebih murah pada expected-cost criterion jika action menghilangkan risiko sepenuhnya."; notes.push("Efektivitas preventive action tidak diberikan; perbandingan mengasumsikan eliminasi risiko penuh. Jika hanya sebagian, hitung residual expected loss."); break;
    case 41: { const m=s.match(/ŷ=([-\d.]+)\+([-\d.]+)x1\+\(([-\d.]+)\)x2/); const x=num(s,/x1=(\d+)/), y=num(s,/x2=(\d+)/); model="ŷ=b₀+b₁x₁+b₂x₂"; out("Prediction",Number(m[1])+Number(m[2])*x+Number(m[3])*y,`${m[1]}+${m[2]}×${x}+(${m[3]})×${y}`); break; }
    case 42: { const a=list(s,"periode"); model="forecast berikut = mean tiga observasi terakhir (contoh metode)"; extra="Checkpoint pembanding: gunakan moving average tiga periode terakhir. Anda tetap dapat mengajukan model lain dalam jawaban terbuka."; out("Forecast MA(3)",mean(a.slice(-3)),`(${a.slice(-3).join("+")})/3`); chart("line","Time series",a); interpretation="Satu siklus 12 periode tidak cukup untuk memastikan seasonality; evaluasi forecast pada data yang tidak dipakai untuk fitting."; break; }
    case 43: { const a=list(s,"Actual"), b=list(s,"Forecast A"), c=list(s,"Forecast B"); model="MAE = Σ|actual−forecast|/n"; out("MAE A",mean(a.map((v,i)=>Math.abs(v-b[i]))),`(${a.map((v,i)=>`|${v}−${b[i]}|`).join("+")})/${a.length}`); out("MAE B",mean(a.map((v,i)=>Math.abs(v-c[i]))),`(${a.map((v,i)=>`|${v}−${c[i]}|`).join("+")})/${a.length}`); decision=outputs[0].value===outputs[1].value?"MAE seri; gunakan kriteria tambahan.":`Pilih ${outputs[0].value<outputs[1].value?"A":"B"} berdasarkan MAE lebih rendah; periksa bias dan biaya error.`; chart("line","Actual",a); break; }
    case 44: model="FV = P(1+r)ᵗ"; out("Future value",n[0]*(1+n[1]/100)**n[2],`${n[0]}×(1+${n[1]}/100)^${n[2]}`,"monetary-unit"); chart("financial","Pertumbuhan modal",Array.from({length:n[2]+1},(_,t)=>n[0]*(1+n[1]/100)**t),"monetary-unit"); break;
    case 45: { const cf=list(s,"flows"), r=num(s,/rate=(\d+)/)/100; model="NPV = Σ CFₜ/(1+r)ᵗ"; out("NPV",sum(cf.map((v,t)=>v/(1+r)**t)),cf.map((v,t)=>`${v}/${1+r}^${t}`).join(" + "),"monetary-unit"); chart("financial","Cash flow",cf,"monetary-unit",cf.map((_,t)=>`t${t}`)); break; }
    case 46: { const p=list(s,"probabilities"), a=list(s,"Outcomes A"), b=list(s,"B="); model="EV = Σ pᵢ × outcomeᵢ"; out("Expected outcome A",sum(p.map((v,i)=>v*a[i])),p.map((v,i)=>`${v}×${a[i]}`).join("+")); out("Expected outcome B",sum(p.map((v,i)=>v*b[i])),p.map((v,i)=>`${v}×${b[i]}`).join("+")); interpretation=`Worst-case teramati A=${Math.min(...a)}, B=${Math.min(...b)}. Expected value sendiri tidak mewakili toleransi risiko.`; break; }
    case 47: { const m=s.match(/y=([\d.]+)\+([\d.]+)x/), x=num(s,/x=(\d+)/), delta=num(s,/sebesar (\d+)/); const b=Number(m[1]), a=Number(m[2]); model="Δy = a Δx; dy/dx=a"; out("Baseline",b+a*x,`${b}+${a}×${x}`); out("New outcome",b+a*(x+delta),`${b}+${a}×(${x}+${delta})`); out("Absolute change",a*delta,`${a}×${delta}`); out("Sensitivity",a,"Δy/Δx"); break; }
    case 48: { const b=num(s,/demand=(\d+)/), multipliers=list(s,"multipliers"); model="scenario demand = base × multiplier"; multipliers.forEach((v,i)=>out(["Downside","Base","Upside"][i],b*v,`${b}×${v}`,"unit")); chart("bar","Demand scenarios",outputs.map(o=>o.value),"unit",outputs.map(o=>o.label)); break; }
    case 49: { const w=list(s,"weights"), a=list(s,"scores A"), b=list(s,"B="); model="score = Σ weightᵢ × normalized scoreᵢ"; out("Score A",sum(w.map((v,i)=>v*a[i])),w.map((v,i)=>`${v}×${a[i]}`).join("+")); out("Score B",sum(w.map((v,i)=>v*b[i])),w.map((v,i)=>`${v}×${b[i]}`).join("+")); decision=`${outputs[0].value===outputs[1].value?"Kedua alternatif seri":`Pilih ${outputs[0].value>outputs[1].value?"A":"B"}`} pada bobot ini; normalisasi harus searah (lebih besar lebih baik).`; break; }
    case 50: { const mu=num(s,/mean=(\d+)/), scale=num(s,/scale≈(\d+)/), caps=list(s,"options"); model="shortage = max(0, demand−capacity); biaya total = biaya capacity + penalti shortage"; extra="Checkpoint: asumsikan demand skenario tinggi = mean + satu uncertainty scale, tanpa menganggap distribusi Normal. Hitung shortage untuk opsi kapasitas terbesar."; out("Shortage pada skenario tinggi",Math.max(0,mu+scale-Math.max(...caps)),`max(0,${mu}+${scale}−${Math.max(...caps)})`,"unit"); chart("bar","Opsi kapasitas",caps,"unit"); notes.push("Biaya kapasitas dan penalti shortage tidak disediakan; rekomendasi optimal harus bersyarat terhadap asumsi biaya eksplisit."); break; }
  }
  if (level>=51 && level<=60) {
    const d=list(s,"demand vector"), c=list(s,"capacity vector"), costs=list(s,"unit-cost vector");
    const totalD=sum(d), totalC=sum(c);
    model=({51:"A = [d c]; margin = c−d",52:"margin = c−d; biaya = kᵀd",53:"vektor margin m=c−d; ||m||₂",54:"komponen margin mᵢ=cᵢ−dᵢ",55:"min Σkᵢcᵢzᵢ; Σcᵢzᵢ≥Σdᵢ; zᵢ∈{0,1}",56:"min kᵀx; Σxᵢ≥Σdᵢ; 0≤xᵢ≤cᵢ",57:"min kᵀx; dᵢ≤xᵢ≤cᵢ",58:"min Σkᵢxᵢⱼ; Σⱼxᵢⱼ≤cᵢ; Σᵢxᵢⱼ=dⱼ",59:"min Σkᵢdⱼzᵢⱼ; Σᵢzᵢⱼ=Σⱼzᵢⱼ=1; dⱼzᵢⱼ≤cᵢ",60:"bandingkan objective dan slack setiap constraint"})[level];
    extra="Checkpoint bersama: demand dan capacity memiliki unit yang sama. Hitung total kapasitas dan margin agregat. Margin agregat tidak menjamin tiap kebutuhan lokal dapat terpenuhi. Untuk contoh pooled model, kapasitas diasumsikan dapat dialihkan antarkategori; biaya adalah biaya per unit output.";
    out("Total kapasitas",totalC,c.join(" + "),keyUnit); out("Margin agregat",totalC-totalD,`${totalC}−${totalD}`,keyUnit);
    const margin=c.map((v,i)=>v-d[i]);
    if(level===53) out("Norma vektor margin",Math.hypot(...margin),`√(${margin.map(v=>`(${v})²`).join("+")})`,keyUnit);
    calculations.push({label:"Kelayakan lokal",expression:`c−d = [${margin.join(", ")}]`,result:margin.every(v=>v>=0)?"Semua demand lokal terpenuhi oleh kapasitas lokal.":"Ada margin negatif: model tanpa transfer tidak feasible."});
    if([51,52,54].includes(level)) calculations.push({label:"Biaya memenuhi demand",expression:costs.map((k,i)=>`${k}×${d[i]}`).join("+"),result:sum(costs.map((k,i)=>k*d[i]))});
    if([55,56,58,60].includes(level)) {
      const sorted=costs.map((k,i)=>({k,c:c[i],i})).sort((a,b)=>a.k-b.k); let remain=totalD,cost=0; const x=c.map(()=>0);
      for(const row of sorted){x[row.i]=Math.min(remain,row.c);remain-=x[row.i];cost+=x[row.i]*row.k;}
      calculations.push({label:"Contoh relaksasi pooled linear",expression:`Urutkan biaya per unit: ${sorted.map(x=>x.k).join(" < ")}; alokasi [${x.join(", ")}]`,result:remain>0?`Tidak feasible; shortage ${remain}`:`Biaya ${cost}; alokasi termurah dengan kapasitas yang bisa dialihkan.`});
      if(level===55){let best=Infinity,bits=[];for(let mask=0;mask<16;mask++){const active=c.map((_,i)=>(mask>>i)&1);const cap=sum(c.map((v,i)=>v*active[i])),value=sum(c.map((v,i)=>v*costs[i]*active[i]));if(cap>=totalD&&value<best){best=value;bits=active;}} calculations.push({label:"Enumerasi 16 subset",expression:"Aktivasi memakai kapasitas penuh; biaya kᵢcᵢ per kategori aktif.",result:Number.isFinite(best)?`z=[${bits.join(", ")}], biaya ${best}`:"Tidak ada subset feasible."});}
    }
    if(level===59){let best=Infinity,path=[];function permute(a,left){if(!left.length){if(a.every((j,i)=>d[j]<=c[i])){const cost=sum(a.map((j,i)=>costs[i]*d[j]));if(cost<best){best=cost;path=a;}}return;}for(const j of left)permute([...a,j],left.filter(k=>k!==j));}permute([],d.map((_,i)=>i));calculations.push({label:"Enumerasi 24 assignment",expression:"Biaya sumber i untuk demand j = kᵢdⱼ (asumsi tanpa biaya rute tambahan).",result:Number.isFinite(best)?`Assignment sumber→demand [${path.map(j=>j+1)}]; biaya minimum ${best}`:"Tidak ada assignment satu-ke-satu yang feasible."});}
    notes.push("Reference tidak mendefinisikan arti target terhadap vektor. Model di atas menguji demand vector; target tambahan harus diperlakukan sebagai constraint terpisah dengan unit dan makna yang dinyatakan.");
    visuals.push({kind:level<55?"matrix":level===58?"supply-chain":"bar",title:"Demand dan kapasitas",unit:keyUnit,summary:"Perbandingan kebutuhan dan kapasitas tiap kategori.",rows:d.map((v,i)=>({name:`Kategori ${i+1}`,value:v,secondary:c[i]}))});
  }
  if(level>=61 && level<=70){
    const edges=[...s.matchAll(/\('([A-D])', '([A-D])', (\d+)\)/g)].map(m=>({from:m[1],to:m[2],value:Number(m[3])}));
    const w=edges.map(e=>e.value), paths=[w[0]+w[2],w[1]+w[3],w[0]+w[4]+w[3]], shortest=Math.min(...paths), longest=Math.max(...paths);
    model=({61:"G=(V,E), adjacency matrix, reachability",62:"d(v)=min[d(u)+w(u,v)]",63:"maksimalkan flow; konservasi node; 0≤fₑ≤cₑ",64:"ES(v)=max[ES(u)+durasi(u,v)]",65:"precedence + resource constraints; earliest feasible start",66:"ROP = demand rate × lead time + safety stock",67:"ρ=λ/μ; W=1/(μ−λ) untuk M/M/1",68:"R_series=∏Rᵢ; R_parallel=1−∏(1−Rᵢ)",69:"sampling seeded → network metric → distribusi output",70:"network representation + feasible allocation + sensitivity"})[level];
    extra="Checkpoint network: anggap edge berarah sesuai urutan pasangan. Untuk jarak, bobot adalah cost; untuk critical path, bobot adalah durasi. Asumsi ini tidak menyamakan cost, durasi, dan kapasitas.";
    if(level===63){const cuts=[w[0]+w[1],w[1]+w[2]+w[4],w[0]+w[3],w[2]+w[3]];out("Maximum flow A→D",Math.min(...cuts),`min-cut = min(${cuts.join(", ")})`,"flow-unit");extra="Checkpoint flow: bobot edge ditafsirkan sebagai kapasitas. Gunakan konservasi flow di B dan C; cari maximum flow dari A ke D.";}
    else if(level===64||level===65) out("Durasi critical path",longest,`max(${paths.join(", ")})`,"time-unit");
    else out("Shortest path A→D",shortest,`min(${paths.join(", ")})`,"cost-unit");
    calculations.push({label:"Enumerasi path DAG",expression:`A-B-D: ${paths[0]}; A-C-D: ${paths[1]}; A-B-C-D: ${paths[2]}`,result:"Tidak ada cycle; semua path A→D sudah diperiksa."});
    if(level>=66){notes.push("Network tidak menyediakan arrival rate, distribusi, probabilitas reliability, holding cost, atau demand rate. Model khusus topik memerlukan asumsi tambahan yang eksplisit; bobot edge bukan probabilitas.");calculations.push({label:"Parameter tambahan untuk model topik",expression:model,result:({66:"Nyatakan D, biaya pesan S, holding H, lead time L; bila EOQ valid, Q*=√(2DS/H). ROP=λL+safety stock.",67:"Nyatakan λ dan μ dengan satuan sama. Jika λ≥μ, steady-state M/M/1 tidak ada; jika λ<μ, L=ρ/(1−ρ).",68:"Tetapkan tiap Rᵢ di [0,1] dan asumsi independensi. Shared components tidak boleh dihitung sebagai path independen.",69:"Nyatakan distribusi bobot positif, seed dan jumlah simulasi; hitung shortest path pada setiap draw lalu mean/quantile. Hasil berubah bila distribusi berubah.",70:"Pisahkan cost, capacity dan time. Optimasi biaya harus memenuhi conservation, demand, serta capacity; uji perubahan demand dan edge bottleneck."})[level]});}
    visuals.push({kind:level===64||level===65?"schedule":"network",title:"Network operasional",unit:level===63?"flow-unit":"bobot edge",summary:"Network berarah A ke B/C, B ke C/D, dan C ke D.",rows:edges.map(e=>({name:`${e.from} → ${e.to}`,value:e.value})),edges});
  }
  if(level>=71 && level<=80){
    const m=s.match(/f\(x\)=(-[\d.]+)x²\+([\d.]+)x\+([\d.]+)/), a=Number(m[1]),b=Number(m[2]),c=Number(m[3]),x=num(s,/sekitar x=(\d+)/); const f=t=>a*t*t+b*t+c;
    model=`f(x)=${a}x²+${b}x+${c}; f′(x)=${2*a}x+${b}`;
    out("f(x) pada titik kajian",f(x),`${a}×${x}²+${b}×${x}+${c}`,"output-unit");
    if([74,79,80].includes(level)){extra="Checkpoint integral: gunakan interval [0,x]. Integral f adalah akumulasi hanya jika f merupakan rate. Untuk probabilitas, normalisasikan f pada interval tersebut dan pastikan nonnegatif.";out("Integral dari 0 sampai x",a*x**3/3+b*x*x/2+c*x,`${a}×${x}³/3+${b}×${x}²/2+${c}×${x}`,"output-unit × input-unit");}
    else out("Turunan pada x",2*a*x+b,`${2*a}×${x}+${b}`,"output-unit/input-unit");
    calculations.push({label:"Stationary point",expression:`f′(x)=0 ⇒ x*=−${b}/(${2*a})`,result:-b/(2*a)});
    if([76,77,78].includes(level)){notes.push("Fungsi sumber hanya mempunyai satu variabel. Pengayaan eksplisit: g(x,y)=f(x)+2y−y²; tidak dianggap data asli.");extra="Pengayaan multivariabel: gunakan g(x,y)=f(x)+2y−y², evaluasi pada y=1. Untuk optimasi terbatas, asumsikan 0≤x≤titik kajian dan 0≤y≤2.";model+="; g(x,y)=f(x)+2y−y²";out("∂g/∂y pada y=1",0,"2−2×1","output-unit/input-unit");calculations.push({label:"Optimum pengayaan",expression:`x*=min(${x},max(0,${-b/(2*a)})); y*=1`,result:f(Math.min(x,Math.max(0,-b/(2*a))))+1});}
    interpretation=`Pada x=${x}, f(x)=${show(f(x))}. Turunan ${show(2*a*x+b)} menunjukkan perubahan lokal; stationary point adalah maksimum tak terbatas karena f″=${2*a}<0. Constraint dapat memindahkan optimum ke batas.`;
    visuals.push({kind:[74,79].includes(level)?"integral":level===71?"derivative":"function",title:"Model kontinu",unit:"output-unit",summary:"Kurva kuadratik sesuai fungsi pada soal.",coefficients:[a,b,c],rows:Array.from({length:31},(_,i)=>({name:show(i*Math.max(x,-b/(2*a))*1.4/30),value:f(i*Math.max(x,-b/(2*a))*1.4/30)}))});
  }
  if(level>=81 && level<=90){
    const initial=num(s,/system=(\d+)/), h=num(s,/size=([\d.]+)/), obs=list(s,"checkpoints"), target=mean(obs);
    model=({81:"dx/dt = k(μ−x); Euler xₙ₊₁=xₙ+h k(μ−xₙ)",82:"first-order response x(t)=μ+(x₀−μ)e^(−kt)",83:"bisection pada f(x)=x−mean(observations)",84:"trapezoid integral = Σ h(yᵢ+yᵢ₊₁)/2",85:"linear interpolation y(t)=y₀+(y₁−y₀)(t−t₀)/h",86:"xₙ₊₁=xₙ+h(μ−xₙ), stop saat residual≤tolerance",87:"state update xₙ₊₁=xₙ+h(μ−xₙ)",88:"bootstrap observed increments dengan seed tetap",89:"MAE = mean |prediction−observation|",90:"bandingkan holdout MAE dan biaya komputasi"})[level];
    notes.push("Reference tidak memberi governing equation atau waktu observasi. Contoh pembanding memakai jarak checkpoint h yang seragam; model relaksasi memakai k=1 dan μ=mean checkpoints. Ini contoh dengan asumsi eksplisit, bukan model unik dari data.");
    extra=`Checkpoint pembanding: ${level===84?"observed checkpoints adalah rate berjarak h; gunakan trapezoid antar-checkpoint":level===85?"interpolasikan titik tengah antara dua checkpoint pertama":level===89||level===90?"gunakan state awal sebagai prediksi konstan pembanding":level===83?"cari akar f(x)=x−mean(checkpoints)":`gunakan μ=mean(checkpoints), k=1 dan satu update Euler x₁=x₀+h(μ−x₀)`}.`;
    if(level===84) out("Integral trapezoid",sum(obs.slice(1).map((v,i)=>h*(v+obs[i])/2)),obs.slice(1).map((v,i)=>`${h}×(${obs[i]}+${v})/2`).join("+"),"state-unit × time-unit");
    else if(level===85) out("Interpolasi titik tengah",(obs[0]+obs[1])/2,`(${obs[0]}+${obs[1]})/2`,"state-unit");
    else if(level===89||level===90) out("MAE baseline konstan",mean(obs.map(v=>Math.abs(v-initial))),`Σ|${initial}−observasi|/${obs.length}`,"state-unit");
    else if(level===83) out("Akar model pembanding",target,`${sum(obs)}/${obs.length}`,"state-unit");
    else out("State setelah satu update",initial+h*(target-initial),`${initial}+${h}×(${show(target)}−${initial})`,"state-unit");
    calculations.push({label:"Validasi model",expression:`μ=${show(target)}; langkah h=${h}; bandingkan prediksi dengan [${obs.join(", ")}]`,result:"Pisahkan galat numerik (step/tolerance) dari galat model. Fitting dan pengujian pada data yang sama tidak membuktikan kemampuan prediksi."});
    if(level===86){const tol=num(s,/tolerance=([\d.]+)/);let state=initial,iterations=0;while(Math.abs(state-target)>tol&&iterations<10000){state+=h*(target-state);iterations++;}calculations.push({label:"Iterasi sampai residual",expression:`|x−μ|≤${tol}`,result:`${iterations} iterasi; x=${show(state)}; residual=${show(Math.abs(state-target))}`});}
    chart("line","Observed checkpoints",obs,"state-unit");
  }
  if(level>=91){
    const demand=num(s,/baseline=(\d+)/),caps=list(s,"capacities"),costs=list(s,"indicators"),unc=num(s,/demand ±(\d+)/)/100,availability=num(s,/availability (\d+)/)/100;
    model=({91:"decision variables xᵢ, objective, assumptions dan constraint yang eksplisit",92:"min (cost, shortage, risk); Pareto dominance",93:"Σxᵢ≥D(1+u); 0≤xᵢ≤availability×capacityᵢ",94:"margin(a,u)=aΣcᵢ−D(1+u)",95:"propagasi interval atau distribusi input ke margin",96:"0≤xᵢ≤a cᵢ zᵢ; zᵢ∈{0,1}",97:"optimasi keputusan terhadap estimasi output simulasi seeded",98:"skenario koheren (demand, capacity, cost) dan dampak stakeholder",99:"integrasikan model demand, capacity, cost dan uncertainty",100:"multi-constraint, sensitivity, trade-off dan justifikasi keputusan"})[level];
    extra="Checkpoint bersama: kapasitas dapat dijumlahkan dan availability berlaku seragam. Hitung kapasitas efektif, demand tinggi, dan margin robust. Cost indicators baru boleh dipakai sebagai biaya per unit jika asumsi tersebut dinyatakan.";
    const effective=sum(caps)*availability, high=demand*(1+unc);
    out("Kapasitas efektif",effective,`${sum(caps)} × ${availability}`,keyUnit); out("Demand tinggi",high,`${demand} × (1+${unc})`,keyUnit); out("Margin robust",effective-high,`${show(effective)}−${show(high)}`,keyUnit);
    calculations.push({label:"Tiga constraint minimum",expression:"xᵢ≥0; xᵢ≤a cᵢ; Σxᵢ≥D_high",result:effective>=high?"Agregat feasible jika transfer antarkapasitas diperbolehkan.":"Tidak feasible tanpa shortage, kapasitas tambahan, atau penurunan demand."});
    calculations.push({label:"Sensitivitas",expression:`∂margin/∂availability = ${sum(caps)}; ∂margin/∂uncertainty = −${demand}`,result:`Tambahan availability 1 poin persen mengubah margin ${show(sum(caps)*.01)}; tambahan uncertainty 1 poin persen mengubah margin ${show(-demand*.01)}.`});
    decision=effective>=high?"Kapasitas agregat cukup pada rentang asumsi; pilih alokasi dengan biaya/risiko yang sesuai dan periksa bottleneck lokal.":`Shortage robust ${show(high-effective)}. Bandingkan penambahan kapasitas, pengurangan demand, atau penerimaan risiko secara eksplisit.`;
    sensitivity=`Batas availability agar feasible adalah ${show(high/sum(caps)*100)}%. Jika di atas 100%, kapasitas nominal pun tidak cukup pada demand tinggi.`;
    visuals.push({kind:"bar",title:"Kapasitas per sumber",unit:keyUnit,summary:"Kapasitas nominal dan efektif dengan availability yang diberikan.",rows:caps.map((v,i)=>({name:`Sumber ${i+1}`,value:v,secondary:v*availability}))});
    if(level===96)calculations.push({label:"Keputusan diskret",expression:"Enumerasi 2⁵ subset sumber aktif, uji kapasitas lalu alokasikan output kontinu.",result:"Biaya aktivasi belum diberikan. Nyatakan biaya tersebut atau hindari klaim optimum aktivasi unik."});
    if(level===95||level===97)calculations.push({label:"Ketidakpastian",expression:"Rentang tidak menentukan distribusi probabilitas.",result:"Untuk Monte Carlo, nyatakan distribusi dan dependensi; gunakan seed, sampling berulang, serta interval estimasi sebelum membandingkan opsi."});
    if(level===92)calculations.push({label:"Pareto",expression:`Biaya indikator per sumber [${costs.join(", ")}]`,result:"Alternatif didominasi bila alternatif lain tidak lebih buruk pada seluruh objective dan lebih baik pada minimal satu. Bobot preferensi harus dinyatakan sebelum memilih satu titik Pareto."});
  }
  if(!outputs.length) throw new Error(`Recipe L${level} belum menghasilkan checkpoint`);
  interpretation ||= outputs.map(o=>`${o.label} sebesar ${show(o.value)} ${o.unit} (${o.expression}).`).join(" ");
  decision ||= "Gunakan hasil untuk objective yang dinyatakan, setelah memeriksa satuan, asumsi, dan batas operasional. Jika ambang keputusan belum diberikan, rekomendasi harus bersyarat.";
  return { outputs, calculations, notes, visuals, model, interpretation, decision, sensitivity, extra };
}
