"use client";
import type { Diagnostic, InteractionSpec, ResponseValue } from "@/domain/question/types";
import { Button } from "@/components/ui/button";
import { ArrowDown, ArrowUp, Check, RotateCcw } from "lucide-react";
export function Interaction({ spec, value = {}, onChange, diagnostic, disabled = false }: { spec: InteractionSpec; value?: ResponseValue; onChange: (value: ResponseValue) => void; diagnostic?: Diagnostic; disabled?: boolean }) {
  const v = spec.validator, errorId = `${spec.id}-feedback`;
  let control;
  if (v.kind === "numeric") control = <><div className="numeric-row"><label className="field"><span>Jawaban</span><input aria-label={spec.prompt} inputMode="decimal" autoComplete="off" value={value.text ?? ""} onChange={e => onChange({ ...value, text: e.target.value })} disabled={disabled} aria-invalid={diagnostic?.score === 0} aria-describedby={`${spec.id}-help ${diagnostic ? errorId : ""}`} placeholder="Masukkan nilai" /></label><label className="field"><span>Satuan</span><input aria-label={`Satuan ${spec.prompt}`} value={value.unit ?? v.unit} onChange={e => onChange({ ...value, unit: e.target.value })} disabled={disabled} /></label></div><p id={`${spec.id}-help`} className="numeric-help">Koma desimal atau pecahan (mis. 1/2) diterima. Toleransi ±{v.tolerance}; tanpa pemisah ribuan.</p></>;
  else if (v.kind === "choice") control = <div>{spec.options?.map((option, index) => <label className="choice" key={option}><input type="radio" name={spec.id} checked={value.text === option} onChange={() => onChange({ text: option })} disabled={disabled} /><span><span className="muted">{String.fromCharCode(65 + index)}.</span> {option}</span></label>)}</div>;
  else if (v.kind === "set") control = <div>{spec.options?.map(option => <label className="choice" key={option}><input type="checkbox" checked={value.selections?.includes(option) ?? false} onChange={e => onChange({ selections: e.target.checked ? [...(value.selections ?? []), option] : value.selections?.filter(x => x !== option) })} disabled={disabled} /><span>{option}</span></label>)}</div>;
  else if (v.kind === "equation" || v.kind === "ordered") {
    const selected = value.selections ?? [];
    const remaining = [...(spec.options ?? [])]; for (const token of selected) { const index = remaining.indexOf(token); if (index !== -1) remaining.splice(index, 1); }
    control = <><p className="numeric-help">Pilih token untuk menambahkan. Klik token terpilih untuk menghapus; semua tombol dapat diakses keyboard.</p><div className="token-workspace" aria-label="Urutan terpilih">{!selected.length && <p>Susun jawaban di sini…</p>}{selected.map((token, index) => <button type="button" disabled={disabled} key={`${token}-${index}`} onClick={() => onChange({ selections: selected.filter((_, idx) => idx !== index) })} aria-label={`Hapus ${token} pada posisi ${index + 1}`}>{index + 1}. {token}</button>)}</div><div className="token-palette">{remaining.map((token, index) => <button type="button" disabled={disabled} key={`${token}-${index}`} onClick={() => onChange({ selections: [...selected, token] })}>{token}</button>)}</div><Button type="button" variant="ghost" size="sm" disabled={disabled} onClick={() => onChange({ selections: [] })}><RotateCcw size={13} />Susun ulang</Button>{v.kind === "ordered" && selected.map((token, index) => <div className="row" key={index}><span>{index + 1}. {token}</span><button type="button" className="icon-control" disabled={disabled || index === 0} aria-label={`Naikkan ${token}`} onClick={() => { const next = [...selected]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; onChange({ selections: next }); }}><ArrowUp size={15} /></button><button type="button" className="icon-control" disabled={disabled || index === selected.length - 1} aria-label={`Turunkan ${token}`} onClick={() => { const next = [...selected]; [next[index + 1], next[index]] = [next[index], next[index + 1]]; onChange({ selections: next }); }}><ArrowDown size={15} /></button></div>)}</>;
  } else if (v.kind === "rubric") control = <><textarea aria-label={spec.prompt} rows={5} value={value.text ?? ""} onChange={e => onChange({ ...value, text: e.target.value })} disabled={disabled} placeholder="Tuliskan langkah, asumsi, dan alasanmu. Gunakan data konkret dari soal." /><div className="rubric"><p><strong>Rubrik mandiri</strong> · Nilai kualitas jawaban sendiri. Hasil ini dicatat terpisah dari penilaian otomatis.</p>{v.criteria.map((criterion, index) => <label key={criterion} className="rubric-row"><span>{criterion}</span><select aria-label={`Rubrik ${index + 1}: ${criterion}`} value={value.rubric?.[index] ?? 0} onChange={e => { const ratings = [...(value.rubric ?? v.criteria.map(() => 0))]; ratings[index] = Number(e.target.value); onChange({ ...value, rubric: ratings }); }} disabled={disabled}><option value={0}>0 — Belum ditunjukkan</option><option value={1}>1 — Sebagian, masih ada kekurangan</option><option value={2}>2 — Lengkap dengan bukti</option></select></label>)}</div></>;
  return <fieldset className="interaction" disabled={disabled}><legend><span className="interaction-type">{spec.type}</span>{spec.prompt}</legend>{control}{diagnostic && <div id={errorId} role="status" className={`feedback ${!diagnostic.automatic ? "self" : diagnostic.score === 100 ? "correct" : ""}`}><strong>{diagnostic.automatic ? diagnostic.score === 100 ? <><Check size={13} className="inline" /> Benar</> : "Perlu ditinjau" : "Penilaian mandiri"}</strong><p>{diagnostic.message}</p></div>}</fieldset>;
}
