export type Dimension = "conceptComplexity" | "variableCount" | "reasoningDepth" | "dataComplexity" | "constraintCount" | "operationComplexity" | "abstractionLevel" | "uncertainty" | "interpretationComplexity" | "decisionComplexity";
export type DifficultyProfile = Record<Dimension, number>;
export type Phase = "formulation" | "model" | "calculation" | "validation" | "interpretation" | "decision";
export type NumericAnswer = { kind: "numeric"; value: number; tolerance: number; unit: string };
export type Validator = NumericAnswer | { kind: "choice"; value: string } | { kind: "set" | "ordered"; values: string[] } | { kind: "equation"; tokens: string[] } | { kind: "rubric"; criteria: string[] };
export type InteractionSpec = { id: string; type: string; phase: Phase; prompt: string; options?: string[]; validator: Validator; weight: number; explanation: string };
export type VariableSpec = { key: string; label: string; value?: number | string; unit: string; role: "known" | "unknown" | "derived"; visibleInitially: boolean };
export type VisualizationKind = "bar" | "line" | "scatter" | "histogram" | "box" | "distribution" | "coordinate" | "geometry" | "flow" | "timeline" | "schedule" | "network" | "supply-chain" | "factory" | "financial" | "matrix" | "feasible" | "function" | "derivative" | "integral" | "vector";
export type VisualizationSpec = { kind: VisualizationKind; title: string; unit: string; summary: string; rows: { name: string; value: number; secondary?: number }[]; edges?: { from: string; to: string; value: number }[]; coefficients?: number[] };
export type Question = {
  id: string; version: number; level: number; difficulty: DifficultyProfile; domain: string;
  scenario: { title: string; context: string; role: string; objective: string };
  problem: string; learningObjectives: string[]; mathematicalTopics: string[];
  competencies: { id: Phase; weight: number }[];
  knownVariables: VariableSpec[]; unknownVariables: VariableSpec[]; units: { symbol: string; dimension: string }[];
  constraints: string[]; assumptions: string[]; dataBlocks: { type: "prose" | "table"; title: string; text?: string; rows?: string[][] }[];
  distractors: { label: string; rationale: string }[]; requiredOutputs: string[];
  recommendedModels: { name: string; equation: string }[]; reasoningSteps: string[];
  interactions: InteractionSpec[]; hints: string[];
  solution: { modelingTranslation: string; variableExplanation: string[]; relevantDataRationale: string[]; assumptionsRationale: string[]; selectedMethod: string; methodRationale: string; calculations: { label: string; expression: string; result: number | string }[]; finalAnswer: string; validation: string[]; interpretation: string; decision: string; alternatives: string[]; sensitivity: string };
  commonMistakes: { tag: string; description: string }[]; formulas: { name: string; expression: string }[];
  visualizations: VisualizationSpec[]; estimatedMinutes: number; tags: string[];
  authoring: { originalModel: string; originalKey: string; notes: string[] };
};
export type QuestionMeta = Pick<Question, "id" | "level" | "domain" | "estimatedMinutes"> & { title: string; topic: string; types: string[]; difficulty: number; competencies: Phase[] };
export type Level = { level: number; topic: string; band: string; complexity: string; count: number };
export type ResponseValue = { text?: string; selections?: string[]; unit?: string; rubric?: number[] };
export type Responses = Record<string, ResponseValue>;
export type Diagnostic = { interactionId: string; phase: Phase; score: number; automatic: boolean; message: string; errorTag?: string };
export type Attempt = { schemaVersion: 1; id: string; questionId: string; variantId: string; level: number; domain: string; topic: string; timestamp: string; elapsedSeconds: number; hints: number; responses: Responses; scratchpad: Record<string, string>; retry: number; diagnostics: Diagnostic[]; verifiedScore: number | null; selfScore: number | null; effectiveScore: number; correct: boolean; reviewOf?: string };
export type MistakeRecord = { schemaVersion: 1; id: string; questionId: string; attemptId: string; variantId: string; errorTags: string[]; timestamp: string; resolved: boolean; revisitCount: number; nextReview: string };
export type Mastery = { score: number; evidenceCount: number; recentTrend: number; selfScore: number; selfEvidenceCount: number };
export type Progress = { schemaVersion: 1; unlockedLevel: number; competencies: Record<Phase, Mastery>; completed: string[]; bookmarks: string[] };
export type Settings = { schemaVersion: 1; theme: "light" | "dark" | "system"; reducedMotion: boolean; difficultyView: "score" | "dimensions" };
export type Draft = { schemaVersion: 1; id: string; responses: Responses; scratchpad: Record<string, string>; hints: number; elapsedSeconds: number; updatedAt: string };
export type Session = { schemaVersion: 1; id: string; mode: "practice" | "assessment"; queue: string[]; index: number; attemptIds: string[]; size: number; band: number; streak: number };
