"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowRight, Bookmark, Check, ChevronRight, LockKeyhole } from "lucide-react";
import curriculum from "@/data/curriculum.json";
import { useApp, useIndex } from "@/features/app-provider";
import { Button } from "@/components/ui/button";
import { phases, phaseLabels } from "@/domain/assessment/engine";
export function PageHeader({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: React.ReactNode }) { return <div className="page-intro"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{children}</div>; }
export function LearningPath() {
  const { progress } = useApp();
  return <div className="page"><PageHeader eyebrow="100 LEVEL · 10 BIDANG" title="Satu langkah lebih mengerti." description="Mulai dari fondasi, lalu hubungkan konsep untuk memecahkan masalah yang lebih kompleks."><Button asChild variant="outline"><Link href="/assessment/">Temukan levelmu <ArrowRight size={16} /></Link></Button></PageHeader><div className="notice">Level berikut terbuka setelah dua dari tiga attempt terakhir mencapai mastery 70. Level terkunci tetap dapat dilihat dalam preview.</div>{Array.from({ length: 10 }, (_, band) => <section className="band" key={band}><div className="band-header"><span className="band-number">{String(band + 1).padStart(2, "0")}</span><div><h2>{curriculum[band * 10].band}</h2><p>Level {band * 10 + 1}–{band * 10 + 10}</p></div></div><div className="level-grid">{curriculum.slice(band * 10, band * 10 + 10).map(level => { const done = progress.completed.filter(id => Number(id.slice(1, 4)) === level.level).length, locked = level.level > progress.unlockedLevel; return <Link href={`/level/?level=${level.level}`} key={level.level} className={`level-card ${locked ? "locked" : ""} ${level.level === progress.unlockedLevel ? "current" : ""}`}><div><span className="level-index">{String(level.level).padStart(2, "0")}</span>{locked ? <LockKeyhole size={14} /> : done ? <Check size={15} /> : <ArrowRight size={15} />}</div><h3>{level.topic}</h3><small>{locked ? "Preview · prasyarat level sebelumnya" : `${done} / 50 selesai`}</small></Link>; })}</div></section>)}</div>;
}
export function Library({ levelMode = false }: { levelMode?: boolean }) {
  const params = useSearchParams(), { data, error } = useIndex(), app = useApp();
  const [search, setSearch] = useState(""), [level, setLevel] = useState(params.get("level") ?? ""), [domain, setDomain] = useState(params.get("domain") ?? ""), [topic, setTopic] = useState(params.get("topic") ?? ""), [type, setType] = useState(""), [status, setStatus] = useState(params.get("status") ?? ""), [difficulty, setDifficulty] = useState(""), [competency, setCompetency] = useState(""), [page, setPage] = useState(0);
  const selectedLevel = curriculum.find(l => l.level === Number(level));
  const types = useMemo(() => [...new Set(data.flatMap(q => q.types))].sort(), [data]), domains = useMemo(() => [...new Set(data.map(q => q.domain))].sort(), [data]);
  const mistakes = new Set(app.mistakes.filter(m => !m.resolved).map(m => m.questionId));
  const filtered = data.filter(q => (!search || `${q.id} ${q.title} ${q.topic} ${q.domain}`.toLowerCase().includes(search.toLowerCase())) && (!level || q.level === Number(level)) && (!domain || q.domain === domain) && (!topic || q.topic === topic) && (!type || q.types.includes(type)) && (!difficulty || (difficulty === "0" ? q.difficulty < 35 : difficulty === "1" ? q.difficulty >= 35 && q.difficulty < 65 : q.difficulty >= 65)) && (!competency || q.competencies.includes(competency as typeof phases[number])) && (!status || status === "completed" && app.progress.completed.includes(q.id) || status === "bookmarked" && app.progress.bookmarks.includes(q.id) || status === "mistakes" && mistakes.has(q.id)));
  const pages = Math.max(1, Math.ceil(filtered.length / 20)), currentPage = Math.min(page, pages - 1);
  const filter = (setter: (s: string) => void) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => { setter(e.target.value); setPage(0); };
  return <div className="page"><PageHeader eyebrow={levelMode ? `LEVEL ${level || "1"} · 50 SOAL` : "5.000 SOAL · KONTEKS NYATA"} title={levelMode ? selectedLevel?.topic ?? "Pilih level" : "Temukan masalah berikutnya."} description={levelMode ? selectedLevel?.complexity ?? "Pilih level pada filter." : "Jelajahi konsep, domain, dan cara berpikir yang ingin kamu latih."} />{levelMode && selectedLevel && <div className="notice mb-5">{selectedLevel.level > app.progress.unlockedLevel ? `Preview: level ${selectedLevel.level - 1} adalah prasyarat. Gunakan asesmen untuk penempatan.` : `Level terbuka. ${app.progress.completed.filter(id => Number(id.slice(1, 4)) === selectedLevel.level).length}/50 soal selesai.`} <Link className="text-link" href="/learn/">Lihat jalur belajar</Link></div>}
  <div className="filter-bar"><label className="field grow"><span>Cari soal</span><input value={search} onChange={filter(setSearch)} placeholder="Topik, domain, atau ID soal…" /></label><label className="field"><span>Level</span><select value={level} onChange={filter(setLevel)}><option value="">Semua level</option>{curriculum.map(l => <option key={l.level} value={l.level}>Level {l.level}</option>)}</select></label><label className="field"><span>Domain</span><select value={domain} onChange={filter(setDomain)}><option value="">Semua domain</option>{domains.map(d => <option key={d}>{d}</option>)}</select></label><label className="field"><span>Status</span><select value={status} onChange={filter(setStatus)}><option value="">Semua soal</option><option value="completed">Selesai</option><option value="bookmarked">Bookmark</option><option value="mistakes">Perlu ditinjau</option></select></label></div>
  <details className="mb-5"><summary>Filter lanjutan</summary><div className="grid-2"><label className="field"><span>Topik</span><select value={topic} onChange={filter(setTopic)}><option value="">Semua topik</option>{curriculum.map(l => <option key={l.topic}>{l.topic}</option>)}</select></label><label className="field"><span>Interaksi</span><select value={type} onChange={filter(setType)}><option value="">Semua interaksi</option>{types.map(t => <option key={t}>{t}</option>)}</select></label><label className="field"><span>Kesulitan</span><select value={difficulty} onChange={filter(setDifficulty)}><option value="">Semua kesulitan</option><option value="0">Fondasi · di bawah 35</option><option value="1">Menengah · 35–64</option><option value="2">Lanjut · 65–100</option></select></label><label className="field"><span>Kompetensi</span><select value={competency} onChange={filter(setCompetency)}><option value="">Semua kompetensi</option>{phases.map(p => <option key={p} value={p}>{phaseLabels[p]}</option>)}</select></label></div></details>
  <div className="row space-between mb-4"><p className="text-xs">{filtered.length.toLocaleString("id-ID")} soal ditemukan</p><Button variant="ghost" size="sm" onClick={() => { setSearch(""); setLevel(""); setDomain(""); setTopic(""); setType(""); setStatus(""); setDifficulty(""); setCompetency(""); setPage(0); }}>Reset filter</Button></div>{error ? <p role="alert">{error}</p> : !data.length ? <p role="status">Memuat indeks soal…</p> : !filtered.length ? <div className="empty-state"><h2>Belum ada yang cocok.</h2><p>Coba ubah filter atau kata pencarian.</p></div> : <div className="question-list">{filtered.slice(currentPage * 20, currentPage * 20 + 20).map(q => <Link key={q.id} href={`/question/?id=${q.id}`} className="question-list-item"><span className="number">{String(q.level).padStart(2, "0")}</span><div><div className="row"><h3>{q.title}</h3>{app.progress.bookmarks.includes(q.id) && <Bookmark size={12} />}{app.progress.completed.includes(q.id) && <Check size={13} />}</div><p>{q.topic} · {q.domain}</p><small>{q.id} · {q.estimatedMinutes} menit · Kesulitan {q.difficulty}{q.level > app.progress.unlockedLevel ? " · Preview" : ""}</small></div><ChevronRight size={17} /></Link>)}</div>}<div className="pagination"><Button variant="outline" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Sebelumnya</Button><span>{currentPage + 1} / {pages}</span><Button variant="outline" disabled={currentPage >= pages - 1} onClick={() => setPage(currentPage + 1)}>Berikutnya</Button></div></div>;
}
export function TopicDomainPage({ mode }: { mode: "topics" | "domains" }) {
  const { data, error } = useIndex();
  const domains = [...new Set(data.map(q => q.domain))].sort();
  return <div className="page"><PageHeader eyebrow="EKSPLORASI" title={mode === "topics" ? "Hubungkan konsepnya." : "Matematika di sekitarmu."} description={mode === "topics" ? "Prasyarat membangun jembatan dari konsep dasar ke pemodelan lanjut." : "Pilih konteks yang dekat dengan tujuan dan pekerjaanmu."} />{error && <p role="alert">{error}</p>}<div className="grid-3">{mode === "topics" ? curriculum.map(l => <Link className="panel" key={l.level} href={`/problems/?topic=${encodeURIComponent(l.topic)}`}><span className="tag">Level {l.level}</span><h3 className="mt-3 mb-2">{l.topic}</h3><p className="text-xs">{l.complexity}</p><p className="text-xs mt-3">Prasyarat: {l.level > 1 ? curriculum[l.level - 2].topic : "Tidak ada"}</p></Link>) : domains.map(d => <Link className="panel" key={d} href={`/problems/?domain=${encodeURIComponent(d)}`}><h3>{d}</h3><p className="text-xs mt-2">{data.filter(q => q.domain === d).length} soal · beragam level dan peran</p><span className="text-link mt-4">Jelajahi domain <ArrowRight size={15} /></span></Link>)}</div></div>;
}
