"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Boxes, Check, ChevronRight, Clock3, Compass, Factory, Lightbulb, Route, TrendingUp } from "lucide-react";
import { useApp } from "@/features/app-provider";
import curriculum from "@/data/curriculum.json";
import { Button } from "@/components/ui/button";
export function Home() {
  const { progress, attempts, session } = useApp(), current = curriculum[progress.unlockedLevel - 1];
  const nextId = session?.queue[session.index] ?? `L${String(current.level).padStart(3, "0")}-Q01`;
  return <div className="page home-page"><div className="page-intro"><div><p className="eyebrow">SEDIKIT LATIHAN, CARA PIKIR YANG BERBEDA</p><h1>Matematika yang <span className="serif-accent">bermakna.</span></h1><p>Belajar melihat masalah, membangun model, dan mengambil keputusan.</p></div><Link className="text-link" href="/guide/">Bagaimana cara belajarnya? <ArrowUpRight size={16} /></Link></div>
    <section className="hero-panel"><div className="hero-copy"><span className="hero-kicker"><span className="small-line" /> PEMIKIRAN NYATA. DAMPAK NYATA.</span><h2>Dunia tidak memberi formula.<br /><em>Kamu yang membangun modelnya.</em></h2><p>Dari mengatur anggaran hingga merancang sistem produksi. Latih kemampuan menerjemahkan situasi nyata menjadi keputusan yang masuk akal.</p><div className="hero-actions"><Button asChild><Link href={`/question/?id=${nextId}`}>{attempts.length ? "Lanjutkan belajar" : "Mulai dari level 1"}<ArrowRight size={18} /></Link></Button><Link href="/assessment/" className="hero-secondary">Temukan levelmu <ChevronRight size={16} /></Link></div><div className="hero-facts"><span><Check size={14} />Tanpa pendaftaran</span><span><Check size={14} />Belajar sesuai ritmemu</span></div></div>
    <div className="hero-diagram" aria-label="Masalah nyata diterjemahkan menjadi model, kemudian keputusan"><div className="diagram-grid" /><span className="diagram-caption">SEBUAH CARA UNTUK BERPIKIR</span><div className="diagram-source"><Factory size={24} /><span>Target produksi<strong>480 unit / shift</strong></span><span className="diagram-tag">KONTEKS</span></div><div className="diagram-connector"><span /><small>identifikasi hubungan</small></div><div className="diagram-equation"><span>MODEL MATEMATIKA</span><p>r = <span className="fraction"><span>target − selesai</span><span>waktu tersedia</span></span></p><small>variabel · satuan · asumsi</small></div><div className="diagram-connector short"><span /></div><div className="diagram-result"><span className="check-circle"><Check size={15} /></span><span>Keputusan dengan alasan.</span><ArrowUpRight size={18} /></div></div></section>
    <section className="stat-strip" aria-label="Ringkasan belajar"><div><span className="stat-icon"><Compass size={21} /></span><strong>100<small>level bertahap</small></strong></div><div><span className="stat-icon"><Boxes size={21} /></span><strong>5.000<small>masalah dunia nyata</small></strong></div><div><span className="stat-icon"><Route size={21} /></span><strong>10<small>bidang pembelajaran</small></strong></div><div><span className="stat-icon"><TrendingUp size={21} /></span><strong>{progress.completed.length}<small>soal kamu selesaikan</small></strong></div></section>
    <div className="home-columns"><section><div className="section-heading"><div><p className="eyebrow">LANGKAH BERIKUTNYA</p><h2>Bangun fondasi yang kuat</h2></div><Link href="/learn/" className="text-link">Lihat jalur <ArrowRight size={15} /></Link></div><Link href={`/level/?level=${current.level}`} className="continue-card"><div className="level-square">{String(current.level).padStart(2, "0")}<small>LEVEL</small></div><div className="continue-copy"><span className="tag">{current.band}</span><h3>{current.topic}</h3><p>{current.complexity}</p><div className="progress-track"><span style={{ width: `${progress.completed.filter(id => Number(id.slice(1, 4)) === current.level).length * 2}%` }} /></div><small>{progress.completed.filter(id => Number(id.slice(1, 4)) === current.level).length} / 50 soal selesai <span>Mulai satu langkah <ArrowRight size={13} /></span></small></div></Link>
    <div className="section-heading compact"><h2>Satu masalah, banyak konteks</h2><Link href="/domains/" className="text-link">Semua domain <ArrowRight size={15} /></Link></div><div className="domain-tiles">{[{ title: "Manufacturing", label: "Produksi & kapasitas", icon: Factory, text: "Cukupkah kapasitas hari ini?" }, { title: "Finance", label: "Keuangan & bisnis", icon: TrendingUp, text: "Pilihan mana yang bernilai?" }, { title: "Logistics", label: "Logistik & operasi", icon: Route, text: "Bagaimana rute terbaiknya?" }].map(({ title, label, icon: Icon, text }) => <Link href={`/problems/?domain=${encodeURIComponent(title)}`} key={title}><Icon size={23} /><h3>{label}</h3><p>{text}</p><ArrowUpRight size={16} className="tile-arrow" /></Link>)}</div></section>
    <aside className="daily-card"><span className="eyebrow"><Lightbulb size={15} /> LATIHAN KECIL HARI INI</span><h2>Berhenti menebak.<br />Mulai memodelkan.</h2><p>Satu tantangan baru setiap hari untuk menjaga rasa ingin tahu dan melatih cara berpikirmu.</p><div className="daily-illustration" aria-hidden="true"><span>?</span><svg viewBox="0 0 180 100"><path d="M10 85H170M25 85V10" /><path d="M25 75L60 65L95 45L130 35L162 15" /><circle cx="95" cy="45" r="5" /></svg></div><div className="daily-bottom"><span><Clock3 size={15} /> Sesuai soal hari ini</span><Button asChild variant="outline"><Link href="/daily/">Buka tantangan <ArrowRight size={16} /></Link></Button></div></aside></div>
    <section className="learning-loop"><p className="eyebrow">BUKAN HANYA JAWABAN YANG BENAR</p><h2>Cara berpikir yang bisa kamu bawa ke mana saja.</h2><div>{["Pahami masalah", "Bangun model", "Hitung & validasi", "Ambil keputusan"].map((text, i) => <span key={text}><small>0{i + 1}</small>{text}{i < 3 && <ArrowRight size={17} />}</span>)}</div></section>
  </div>;
}
