"use client";
import { useState } from "react";
import Link from "next/link";
import dynamic from "next/dynamic";
import { ArrowRight, Check, RotateCcw } from "lucide-react";
import { useApp } from "@/features/app-provider";
import { phaseLabels, phases } from "@/domain/assessment/engine";
import { formatNumber } from "@/lib/utils";
import { PageHeader } from "./catalog";
import { Button } from "@/components/ui/button";
const ChartBlock = dynamic(() => import("@/components/visualization/chart-block"), { ssr: false });
export function ProgressPage({ statistics = false }: { statistics?: boolean }) {
  const { progress, attempts } = useApp();
  const accuracy = attempts.length ? attempts.filter(a => a.correct).length / attempts.length * 100 : 0;
  const first = attempts.filter(a => !a.retry), noHint = attempts.filter(a => !a.hints);
  const average = attempts.length ? attempts.reduce((sum, a) => sum + a.elapsedSeconds, 0) / attempts.length / 60 : 0;
  const ordered = [...attempts].sort((a, b) => a.timestamp.localeCompare(b.timestamp));
  const groups = [...new Set(attempts.map(a => statistics ? a.domain : a.topic))].map(name => { const rows = attempts.filter(a => (statistics ? a.domain : a.topic) === name); return { name, value: rows.reduce((sum, a) => sum + (a.verifiedScore ?? 0), 0) / rows.length, count: rows.length }; }).sort((a, b) => a.value - b.value);
  return <div className="page"><PageHeader eyebrow={statistics ? "STATISTIK LOKAL" : "PERKEMBANGAN BELAJARMU"} title={statistics ? "Pola di balik latihanmu." : "Lihat cara pikirmu bertumbuh."} description="Kemajuan dilihat dari bukti latihan. Skor otomatis dan penilaian mandiri memiliki catatan terpisah."><Button asChild variant="outline"><Link href={statistics ? "/progress/" : "/statistics/"}>{statistics ? "Profil kompetensi" : "Statistik lengkap"}<ArrowRight size={16} /></Link></Button></PageHeader>
  <div className="grid-3 mb-6">{[["Soal selesai",String(progress.completed.length),"dari 5.000 soal"],["Akurasi checkpoint",`${formatNumber(accuracy)}%`,`${attempts.length} attempts tersimpan`],["Waktu rata-rata",`${formatNumber(average)} mnt`,"hanya waktu tab aktif"]].map(([name,value,detail])=><div className="metric" key={name}><p>{name}</p><strong>{value}</strong><small>{detail}</small></div>)}</div>
  {!attempts.length ? <div className="empty-state"><h2>Setiap latihan menjadi bukti.</h2><p>Belum ada attempt tersimpan. Selesaikan satu soal untuk mulai melihat kekuatan dan area yang perlu dilatih.</p><Button asChild><Link href="/practice/">Mulai latihan <ArrowRight size={16}/></Link></Button></div> : <div className="stack"><section className="panel"><div className="section-heading"><h2>Profil kompetensi</h2><span className="badge-muted">EWMA · bukti terbaru lebih relevan</span></div><div className="grid-3">{phases.map(p=>{const m=progress.competencies[p];return <div key={p}><h3>{phaseLabels[p]}</h3><div className="progress-track"><span style={{width:`${m.score}%`}} /></div><p className="text-xs">Terverifikasi: <strong>{formatNumber(m.score)}</strong> · {m.evidenceCount} bukti</p><p className="text-xs mt-1">Mandiri: {formatNumber(m.selfScore)} · {m.selfEvidenceCount} bukti</p><p className="text-xs mt-1">Perubahan terakhir: {m.recentTrend>=0?"+":""}{formatNumber(m.recentTrend)}</p></div>;})}</div></section><div className="grid-2"><section className="panel"><ChartBlock spec={{kind:"line",title:"Tren skor terverifikasi",unit:"persen",summary:"Skor otomatis setiap attempt; tidak menggabungkan rubrik mandiri.",rows:ordered.slice(-30).map((a,i)=>({name:String(i+1),value:a.verifiedScore??0}))}} /></section><section className="panel stack"><h2>Belajar lebih mandiri</h2><p className="text-sm">First-attempt accuracy: <strong>{formatNumber(first.filter(a=>a.correct).length/Math.max(1,first.length)*100)}%</strong> ({first.length} bukti)</p><p className="text-sm">No-hint accuracy: <strong>{formatNumber(noHint.filter(a=>a.correct).length/Math.max(1,noHint.length)*100)}%</strong> ({noHint.length} bukti)</p><p className="text-sm">Attempt dengan hint: <strong>{formatNumber(attempts.filter(a=>a.hints>0).length/attempts.length*100)}%</strong></p><p className="text-sm">Level terbuka: <strong>{progress.unlockedLevel}</strong> dari 100</p><Link href="/mistakes/" className="text-link">Belajar dari kesalahan <ArrowRight size={15}/></Link></section></div><section className="panel"><h2 className="mb-4">{statistics?"Performa berdasarkan domain":"Topik yang membutuhkan perhatian"}</h2><div className="table-scroll"><table><thead><tr><th>{statistics?"Domain":"Topik"}</th><th>Skor otomatis rata-rata</th><th>Bukti</th></tr></thead><tbody>{groups.map(g=><tr key={g.name}><td>{g.name}</td><td>{formatNumber(g.value)}%</td><td>{g.count}</td></tr>)}</tbody></table></div></section></div>}</div>;
}
export function MistakePage() {
  const {mistakes,attempts}=useApp(),[category,setCategory]=useState(""),[status,setStatus]=useState("open"),[selected,setSelected]=useState<string>();
  const tags=[...new Set(mistakes.flatMap(m=>m.errorTags))].sort();
  const rows=mistakes.filter(m=>(!category||m.errorTags.includes(category))&&(status==="all"||status==="resolved"&&m.resolved||status==="open"&&!m.resolved||status==="due"&&!m.resolved&&new Date(m.nextReview)<=new Date())).sort((a,b)=>a.nextReview.localeCompare(b.nextReview));
  return <div className="page"><PageHeader eyebrow="KESALAHAN ADALAH INFORMASI" title="Temukan bagian yang terlewat." description="Tinjau kembali model, data, dan satuan. Jawaban lama disembunyikan sampai kamu memilih melihat riwayat."/><div className="filter-bar"><label className="field grow"><span>Kategori kesalahan</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Semua kategori</option>{tags.map(t=><option key={t}>{t}</option>)}</select></label><label className="field"><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Perlu ditinjau</option><option value="due">Jatuh tempo</option><option value="resolved">Terselesaikan</option><option value="all">Seluruh riwayat</option></select></label></div>{!rows.length?<div className="empty-state"><h2>Belum ada kesalahan pada filter ini.</h2><p>Kesalahan dari pemeriksaan otomatis akan tersimpan di sini. Penilaian mandiri tidak dianggap diagnosis otomatis.</p><Button asChild variant="outline"><Link href="/practice/">Kembali berlatih</Link></Button></div>:<div className="stack">{rows.map(m=>{const a=attempts.find(a=>a.id===m.attemptId);return <article className="panel" key={m.id}><div className="row space-between"><div><h3>{m.questionId} · {a?.topic}</h3><p className="text-xs mt-1">{m.errorTags.join(" · ")}</p><p className="text-xs mt-1">Tinjau: {new Date(m.nextReview).toLocaleDateString("id-ID")} · {m.resolved?"Terselesaikan":"Belum terselesaikan"}</p></div><Button asChild variant="outline"><Link href={`/question/?id=${m.questionId}&review=${encodeURIComponent(m.id)}`}>{m.resolved?<Check size={15}/>:<RotateCcw size={15}/>}Coba lagi</Link></Button></div><Button className="mt-3" size="sm" variant="ghost" onClick={()=>setSelected(selected===m.id?undefined:m.id)}>{selected===m.id?"Sembunyikan riwayat":"Lihat attempt lama (membuka jawaban)"}</Button>{selected===m.id&&a&&<div className="prose"><p>Attempt {new Date(a.timestamp).toLocaleString("id-ID")} · Skor otomatis {formatNumber(a.verifiedScore??0)}%</p>{Object.entries(a.responses).map(([id,r])=><p key={id}><strong>{id}:</strong> {r.text??r.selections?.join(" → ")}</p>)}{Object.entries(a.scratchpad).map(([key,value])=>value&&<p key={key}><strong>{key}:</strong> {value}</p>)}</div>}</article>;})}</div>}</div>;
}
