"use client";
import { useState } from "react";
import { Download, Upload } from "lucide-react";
import { useApp } from "@/features/app-provider";
import * as storage from "@/persistence/storage";
import { Button } from "@/components/ui/button";
import { PageHeader } from "./catalog";
function download(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function SettingsPage(){
  const app=useApp(),[message,setMessage]=useState(""),[pending,setPending]=useState<storage.Backup>(),[reset,setReset]=useState(""),[busy,setBusy]=useState(false),[offline,setOffline]=useState(0);
  async function exportData(){try{download(JSON.stringify(await storage.exportBackup(),null,2),`modelmath-progress-${new Date().toISOString().slice(0,10)}.json`);setMessage("Ekspor siap diunduh.");}catch(e){setMessage(String(e));}}
  async function readImport(file:File|undefined){if(!file)return;setPending(undefined);try{if(file.size>50_000_000)throw Error("Batas impor 50 MB.");const data=storage.parseBackup(await file.text());setPending(data);setMessage("File valid. Periksa ringkasan sebelum mengganti data lokal.");}catch(e){setMessage(`Impor ditolak: ${String(e)}`);}}
  async function offlineBank(){setBusy(true);setMessage("");try{if(!("serviceWorker" in navigator))throw Error("Browser tidak mendukung cache offline.");await navigator.serviceWorker.ready;for(let l=1;l<=100;l++){const response=await fetch(`/content/level-${String(l).padStart(3,"0")}.json`);if(!response.ok)throw Error(`Gagal mengunduh level ${l}`);await response.arrayBuffer();setOffline(l);}setMessage("100 level selesai dimuat. Aset aplikasi akan dicache oleh service worker.");}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  return <div className="page"><PageHeader eyebrow="PENGATURAN & DATA" title="Ruang belajar, sesuai kebutuhanmu." description="Atur tampilan, simpan salinan progress, dan kelola data perangkat."/><div className="grid-2"><section className="panel stack"><h2>Tampilan</h2><label className="field"><span>Tema</span><select value={app.settings.theme} onChange={e=>app.configure({...app.settings,theme:e.target.value as typeof app.settings.theme})}><option value="system">Ikuti perangkat</option><option value="light">Terang</option><option value="dark">Gelap</option></select></label><label className="checkbox-row"><input type="checkbox" checked={app.settings.reducedMotion} onChange={e=>app.configure({...app.settings,reducedMotion:e.target.checked})}/>Kurangi animasi</label><label className="field"><span>Tampilan kesulitan</span><select value={app.settings.difficultyView} onChange={e=>app.configure({...app.settings,difficultyView:e.target.value as typeof app.settings.difficultyView})}><option value="score">Skor ringkas</option><option value="dimensions">Sepuluh dimensi</option></select></label><p className="text-xs">Pengaturan reduced motion dari sistem juga selalu dihormati.</p></section>
  <section className="panel stack"><h2>Cadangan progress</h2><p>Ekspor mencakup attempt, scratchpad, mistake, bookmark, sesi, dan pengaturan. Impor menggantikan data setelah Anda memeriksa ringkasannya.</p><Button variant="outline" onClick={exportData}><Download size={16}/>Ekspor progress JSON</Button><label className="field"><span><Upload size={14} className="inline"/> Pilih file untuk diimpor</span><input type="file" accept="application/json,.json" onChange={e=>readImport(e.target.files?.[0])}/></label>{pending&&<div className="notice"><p>{pending.attempts.length} attempts · {pending.mistakes.length} mistakes · level {pending.progress.unlockedLevel}.</p><p>Diekspor {new Date(pending.exportedAt).toLocaleString("id-ID")}. Data lokal saat ini akan diganti.</p><div className="row mt-3"><Button disabled={busy} onClick={async()=>{setBusy(true);try{await storage.importBackup(pending);await app.refresh();setPending(undefined);setMessage("Impor berhasil; data lokal telah diperbarui.");}catch(e){setMessage(String(e));}finally{setBusy(false);}}}>Ganti data dengan impor ini</Button><Button variant="ghost" onClick={()=>setPending(undefined)}>Batal</Button></div></div>}</section>
  <section className="panel stack"><h2>Konten offline</h2><p>Konten per level dicache saat dibuka. Anda juga dapat memuat seluruh 5.000 soal sekarang. Pastikan tersedia ruang penyimpanan browser.</p><Button variant="outline" disabled={busy||process.env.NODE_ENV!=="production"} onClick={offlineBank}>{busy?`Memuat level ${offline}/100…`:"Simpan seluruh bank untuk offline"}</Button>{process.env.NODE_ENV!=="production"&&<p className="text-xs">Cache offline tersedia pada production build.</p>}<p className="text-xs">Browser dapat menghapus cache ketika ruang perangkat penuh. Ekspor progress untuk salinan yang Anda kelola sendiri.</p></section>
  <section className="panel stack"><h2>Pemulihan data</h2><p>Jika versi data tidak dapat dibaca, simpan data mentah sebelum melakukan reset. Ekspor pemulihan ditujukan untuk pemeriksaan teknis dan tidak diimpor sebagai progress biasa.</p><Button variant="outline" onClick={async()=>{try{download(await storage.exportRawRecovery(),"modelmath-recovery.json");setMessage("Data pemulihan siap diunduh.");}catch(e){setMessage(String(e));}}}>Ekspor data mentah</Button></section></div>
  <section className="panel danger-zone mt-6 stack"><h2>Reset progress lokal</h2><p>Ini menghapus seluruh progress, attempt, scratchpad, bookmark, dan pengaturan ModelMath di browser ini. Ekspor salinan sebelum melanjutkan.</p><label className="field max-w-sm"><span>Ketik RESET untuk mengonfirmasi penghapusan</span><input value={reset} onChange={e=>setReset(e.target.value)} placeholder="RESET"/></label><Button className="w-fit" variant="destructive" disabled={reset!=="RESET"||busy} onClick={async()=>{setBusy(true);try{await storage.resetData();await app.refresh();setReset("");setMessage("Data lokal telah direset.");}catch(e){setMessage(String(e));}finally{setBusy(false);}}}>Hapus data lokal</Button></section>{message&&<p className="notice mt-5" role="status">{message}</p>}</div>;
}
